version: '3'

services:
  simple-ad-placement-service:
    build: .
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    
  mysql:
    container_name: db_mysql
    image: mysql:5.7
    restart: always
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: jjshen
      MYSQL_DATABASE: ads
